version: '2'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src
      - node_modules:/usr/src/node_modules
volumes:
  node_modules:
